lib/server_web/router.ex
defmodule ServerWeb.Router do
  use ServerWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end

  pipeline :auth do
    plug(Server.Auth.Pipeline)
  end

  scope "/", ServerWeb do
    pipe_through([:browser, :auth])

    get("/", PageController, :index)
    resources("/us__ers", Us__erController)

    get("/login", SessionController, :login)
    get("/register", ParentController, :registration)
    get("/logout", SessionController, :delete)
    resources("/menus", MenuController, only: [:index])
    resources("/menu", MenuController, except: [:index])
    resources("/sessions", SessionController, only: [:new, :create, :delete], singleton: true)

    resources("/administrators", AdministratorController)

    # done
    resources "/parents", ParentController do
      # done
      resources("/wallet", ParentWalletController, expect: [:index])

      resources("/orders", OrderController)
      get("/delete_order", OrderController, :delete_order)

      # done
      resources("/children", ParentChildController)

      # resources "/orders", ParentOrderController
    end

    resources "/caterings", CateringController do
      get("/orders", OrderController, :orders)
      # done
      resources("/menus", CateringMenuController)
      # done
      resources("/foods", CateringFoodController)
    end

    # done
    resources "/schools", SchoolController do
      # done
      resources("/children", SchoolChildController)
    end

    # done - show page to be finished when bracelet is checked
    resources("/hosts", HostController)
  end

  # Other scopes may use custom stacks.
  # scope "/api", ServerWeb do
  #   pipe_through :api
  # end
end

lib/server_web/controllers/parent/parent_wallet_controller.ex
defmodule ServerWeb.ParentWalletController do
  use ServerWeb, :controller

  # def index(conn, params) do
  #   parent = Server.Accounts.get_parent!(params["parent_id"])
  #   render(conn, "index.html", parent: parent)
  # end

  def new(conn, _params) do
    render(conn, "index.html")
  end

  def create(conn, _params) do
    render(conn, "index.html")
  end

  def show(conn, params) do
    parent = Server.Accounts.get_parent!(params["parent_id"])
    render(conn, "show.html", parent: parent)
  end

  def edit(conn, _params) do
    render(conn, "index.html")
  end

  def update(conn, params) do
    id = params["id"]
    money = params["update"]["money"]["money"]
    {balance, rest} = Float.parse(money)
    parent = Server.Accounts.get_parent!(id)
    final = balance + parent.money
    updated = Server.Accounts.update_parent(parent, %{"money" => Float.to_string(final)})

    parent = Server.Accounts.get_parent!(params["parent_id"])

    conn
    |> put_flash(:info, "Упешно добавени пари в акаунта!")
    |> render("show.html", parent: parent)
    |> halt()
  end

  def delete(conn, _params) do
    render(conn, "index.html")
  end
end

lib/server_web/views/parent/parent_wallet_view.ex
defmodule ServerWeb.ParentWalletView do
  use ServerWeb, :view
end

lib/server_web/templates/parent_wallet/show.html.eex
    

<div class="row">
    <div class="form-outline">
        <div class="balance" style="margin-bottom: 5%;">
            <span class="title"> Баланс: </span> 
            <span class="money">
            <%= 
                if @parent.money != nil do
                    price = (@parent.money)
                            |> Decimal.from_float() |> Decimal.round(2) |> Decimal.to_string 
                            Enum.join([price, "лв."]," ")
                else
                    0
                end 
            %>
            </span>
        </div>

        <div class="title">Добавяне на пари в акаунта</div>
        
        <%= form_for @conn, Routes.parent_parent_wallet_path(@conn , :update, @parent.id, @conn.assigns.parent.id),[ method: :put, as: :update, class: "reg-forms" ], fn f -> %>
                    <%= inputs_for f, :money, fn pdf -> %>

                <%= text_input pdf, :name, [ class: "form-control" ,minlength: "3", required: true , placeholder: "Име",  type: "text" , value: ""] %>
                <%= text_input pdf, :card, [ class: "form-control" ,minlength: "16", maxlength: "16", required: true , placeholder: "Номер на карта",  type: "text" , value: ""] %>
                <%= text_input pdf, :cvc, [ class: "form-control" ,minlength: "3", maxlength: "3", required: true , placeholder: "CVC на карта",  type: "text" , value: ""] %>
                <%= text_input pdf, :month, [ class: "form-control" ,minlength: "2", maxlength: "2", required: true , placeholder: "MM",  type: "text" , value: ""] %>
                <%= text_input pdf, :year, [ class: "form-control" ,minlength: "2", maxlength: "2", required: true , placeholder: "YY",  type: "text" , value: ""] %>
                <%= number_input pdf, :money, [ class: "form-control" ,step: "0.01", required: true , placeholder: "Сума", value: ""] %>
            
            <% end %>
            <%= submit "Добави", [class: "btn btn-primary"] %>
            <%= link "Назад", to: Routes.parent_path(@conn, :show, @parent.id), class: "btn btn-primary" %>
        <% end %>
    </div>
</div>