lib/server_web/router.ex
defmodule ServerWeb.Router do
  use ServerWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end

  pipeline :auth do
    plug(Server.Auth.Pipeline)
  end

  scope "/", ServerWeb do
    pipe_through([:browser, :auth])

    get("/", PageController, :index)
    resources("/us__ers", Us__erController)

    get("/login", SessionController, :login)
    get("/register", ParentController, :registration)
    get("/logout", SessionController, :delete)
    resources("/menus", MenuController, only: [:index])
    resources("/menu", MenuController, except: [:index])
    resources("/sessions", SessionController, only: [:new, :create, :delete], singleton: true)

    resources("/administrators", AdministratorController)

    # done
    resources "/parents", ParentController do
      # done
      resources("/wallet", ParentWalletController, expect: [:index])

      resources("/orders", OrderController)
      get("/delete_order", OrderController, :delete_order)

      # done
      resources("/children", ParentChildController)

      # resources "/orders", ParentOrderController
    end

    resources "/caterings", CateringController do
      get("/orders", OrderController, :orders)
      # done
      resources("/menus", CateringMenuController)
      # done
      resources("/foods", CateringFoodController)
    end

    # done
    resources "/schools", SchoolController do
      # done
      resources("/children", SchoolChildController)
    end

    # done - show page to be finished when bracelet is checked
    resources("/hosts", HostController)
  end

  # Other scopes may use custom stacks.
  # scope "/api", ServerWeb do
  #   pipe_through :api
  # end
end

lib/server/accounts/catering.ex
defmodule Server.Accounts.Catering do
  use Ecto.Schema
  import Ecto.Changeset

  schema "caterings" do
    field :name, :string
    # field :email, :string
    has_many :foods, Server.Catering.Food
    belongs_to :credential, Server.Accounts.Credential
    belongs_to :address, Server.Addressess.Address
    has_many :order, Server.Orders.Order
    timestamps()
  end

  @doc false
  def changeset(catering, attrs \\ %{}) do
    catering
    |> cast(attrs, [:name])
    |> validate_required([:name])
  end
end

lib/server/catering.ex
defmodule Server.Catering do
  @moduledoc """
  The Catering context.
  """

  import Ecto.Query, warn: false
  alias Server.Repo

  alias Server.Catering.FoodType
  alias Server.Catering.Food
  alias Server.Catering.Menu

  @doc """
  Returns the list of food_types.

  ## Examples

      iex> list_food_types()
      [%FoodType{}, ...]

  """
  def list_food_types do
    Repo.all(FoodType)
  end

  @doc """
  Gets a single food_type.

  Raises `Ecto.NoResultsError` if the Food type does not exist.

  ## Examples

      iex> get_food_type!(123)
      %FoodType{}

      iex> get_food_type!(456)
      ** (Ecto.NoResultsError)

  """
  def get_food_type!(id) do
    Repo.get!(FoodType, id)
  end

  @doc """
  Creates a food_type.

  ## Examples

      iex> create_food_type(%{field: value})
      {:ok, %FoodType{}}

      iex> create_food_type(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_food_type(attrs \\ %{}) do
    %FoodType{}
    |> FoodType.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a food_type.

  ## Examples

      iex> update_food_type(food_type, %{field: new_value})
      {:ok, %FoodType{}}

      iex> update_food_type(food_type, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_food_type(%FoodType{} = food_type, attrs) do
    food_type
    |> FoodType.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a FoodType.

  ## Examples

      iex> delete_food_type(food_type)
      {:ok, %FoodType{}}

      iex> delete_food_type(food_type)
      {:error, %Ecto.Changeset{}}

  """
  def delete_food_type(%FoodType{} = food_type) do
    Repo.delete(food_type)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking food_type changes.

  ## Examples

      iex> change_food_type(food_type)
      %Ecto.Changeset{source: %FoodType{}}

  """
  def change_food_type(%FoodType{} = food_type) do
    FoodType.changeset(food_type, %{})
  end

  

  def new_food(attrs) do
    Food.changeset(%Food{},attrs)
  end

  def delete_menu(id) do
    Repo.get!(Menu, id)
    |> Repo.delete()
  end

  def new_menu(attrs) do
    Menu.changeset(%Menu{},attrs)
    |> Repo.insert()
  end

  def list_menus do
    Repo.all(Menu)
  end

  def get_menu(id) do
    Menu
    |> Repo.get!(id)
  end

  @doc """
  Returns the list of foods.

  ## Examples

      iex> list_foods()
      [%Food{}, ...]

  """
  def list_foods do
    Repo.all(Food)
  end

  def get_starters(id) do
    query = from f in Food, where: f.food_type == "1" and f.catering_id == ^id
    Repo.all(query)
  end

  def get_main(id) do
    query = from f in Food, where: f.food_type == "2" and f.catering_id == ^id
    Repo.all(query)
  end

  def get_dessert(id) do
    query = from f in Food, where: f.food_type == "3" and f.catering_id == ^id
    Repo.all(query)
  end

  @doc """
  Gets a single food.

  Raises `Ecto.NoResultsError` if the Food does not exist.

  ## Examples

      iex> get_food!(123)
      %Food{}

      iex> get_food!(456)
      ** (Ecto.NoResultsError)

  """
  def get_food!(id) do
    Food
    |> Repo.get!(id)
    # |> transform_food_type()
  end

  defp transform_food_type(%Food{food_type: ft_id} = food) do
    structureless_food =
      food
      |> Map.from_struct()
      |> put_in([:food_type], Server.Catering.get_food_type!(ft_id).name)

    struct(%Food{}, structureless_food)
  end

  @doc """
  Creates a food.

  ## Examples

      iex> create_food(%{field: value})
      {:ok, %Food{}}

      iex> create_food(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_food(attrs \\ %{}) do
    %Food{}
    |> Food.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a food.

  ## Examples

      iex> update_food(food, %{field: new_value})
      {:ok, %Food{}}

      iex> update_food(food, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_food(%Food{} = food, attrs) do
    food
    |> Food.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Food.

  ## Examples

      iex> delete_food(food)
      {:ok, %Food{}}

      iex> delete_food(food)
      {:error, %Ecto.Changeset{}}

  """
  def delete_food(%Food{} = food) do
    Repo.delete(food)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking food changes.

  ## Examples

      iex> change_food(food)
      %Ecto.Changeset{source: %Food{}}

  """
  def change_food(%Food{} = food) do
    Food.changeset(food, %{})
  end
  
  def change_menu(%Menu{} = menu) do
    Menu.changeset(menu, %{})
  end

  

end

lib/server/catering/food.ex
defmodule Server.Catering.Food do
  use Ecto.Schema
  import Ecto.Changeset

  @all_fields ~w(food_type name price description catering_id)a

  schema "foods" do
    field :food_type
    field :name, :string
    field :price, :float
    field :description, :string
    belongs_to :catering, Server.Accounts.Catering
    has_many :menu, Server.Catering.Menu
    # many_to_many :menus, Server.Catering.Menu, join_through: "menus_foods"

    timestamps()
  end

  @doc false
  def changeset(food, attrs) do
    food
    |> cast(attrs, @all_fields)
    |> validate_required(@all_fields)
  end
end

lib/server/catering/food_type.ex
defmodule Server.Catering.FoodType do
  use Ecto.Schema
  import Ecto.Changeset
  schema "food_types" do
    field :name, :string
    timestamps()
  end

  @doc false
  def changeset(food_type, attrs) do
    food_type
    |> cast(attrs, [:name])
    |> validate_required([:name])
  end
end

lib/server_web/controllers/catering/catering_controller.ex
defmodule ServerWeb.CateringController do
  use ServerWeb, :controller

  alias Server.Accounts
  alias Server.Accounts.Catering
  alias Server.Addressess
  alias Server.Repo
  alias Server.Accounts.Credential

  def index(conn, _params) do
    conn
    |> assign(:cities, Addressess.list_cities(:names))
    |> assign(:caterings, Accounts.list_caterings())
    |> render("index.html")
  end

  def new(conn, _params) do
    conn
    |> assign(:cities, Addressess.list_cities(:names))
    |> assign(:changeset, Accounts.change_catering())
    |> render("new.html")
  end

  def create(conn, %{"catering" => catering_params} = _params) do
    case Accounts.create_catering(catering_params) do
      {:ok, %Catering{} = catering} ->
        conn
        |> put_flash(:info, "Упешно регистриран акаунт!")
        |> redirect(to: Routes.catering_path(conn, :show, catering))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:error, "Грешка при регистрация!")
        |> assign(:cities, Addressess.list_cities(:names))
        |> assign(:changeset, changeset)
        |> render("new.html")
    end
  end

  def delete(conn, %{"id" => id} = params) do
    {:ok, _catering} =
      id
      |> Accounts.get_catering!()
      |> Accounts.delete_catering()

    conn
    |> put_flash(:info, "Успешно изтрита кетъринг фирма.")
    |> redirect(to: Routes.catering_path(conn, :index))
  end

  def show(conn, %{"id" => id} = params) do
    conn
    |> assign(:catering, Accounts.get_catering!(id))
    |> render("show.html")
  end

  def edit(conn, %{"id" => id} = params) do
    catering =
      Accounts.get_catering!(id)
      |> Repo.preload(:address)

    assign = [
      catering: catering,
      changeset: Accounts.change_catering(catering),
      cities: Addressess.list_cities(:names)
    ]

    render(conn, "edit.html", assign)
  end

  def update(conn, %{"id" => id, "catering" => catering_params} = params) do
    catering =
      id
      |> Accounts.get_catering!()
      |> Repo.preload(:address)

    case Accounts.update_catering(catering, catering_params) do
      {:ok, updated_catering} ->
        new_assign_conn =
          conn
          |> assign(:catering, updated_catering)
          |> assign(:changeset, updated_catering)
          |> assign(:cities, Addressess.list_cities(:names))

        new_assign_conn
        |> put_flash(:info, "Успешно обновена информация.")
        |> redirect(to: Routes.catering_path(new_assign_conn, :show, catering))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", catering: catering, changeset: changeset)
    end
  end

  defp parse_cities(cities) do
    Enum.map(cities, fn %Server.Addressess.Address{id: id, city: name} -> {name, id} end)
  end
end

lib/server_web/controllers/catering/catering_food_controller.ex
defmodule ServerWeb.CateringFoodController do
  use ServerWeb, :controller

  alias Server.{Repo, Accounts}
  alias Server.Catering, as: Catering
  alias Catering.Food, as: Food
  alias Catering.FoodType, as: FoodType

  def index(conn, %{"catering_id" => cid}) do
    %Server.Accounts.Catering{foods: foods} =
      Accounts.get_catering!(cid)
      |> Repo.preload(:foods)

    render(conn, "index.html",
      catering_id: cid,
      foods: foods
    )
  end

  def new(conn, params) do
    food = Catering.change_food(%Food{})

    render(conn, "new.html",
      catering_id: params["catering_id"],
      food: food,
      food_types: parse_food_types(Catering.list_food_types())
    )
  end

  def create(conn, %{"food" => food_params, "catering_id" => cid}) do
    case Catering.create_food(Map.put(food_params, "catering_id", cid)) do
      {:ok, food_id} ->
        conn
        |> put_flash(:info, "Успешно добавена храна!")
        |> redirect(to: Routes.catering_catering_food_path(conn, :show, cid, food_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:info, "Грешка при добавянето на храна!")
        |> render("new.html",
          catering_id: cid,
          food: changeset,
          food_types: parse_food_types(Server.Catering.list_food_types())
        )
    end
  end

  def show(conn, %{"id" => id, "catering_id" => cid}) do
    food = Server.Catering.get_food!(id)
    render(conn, "show.html", catering_id: cid, food: food)
  end

  def edit(conn, %{"id" => food_id, "catering_id" => cid}) do
    changeset = food_id |> Server.Catering.get_food!() |> Server.Catering.change_food()

    render(conn, "edit.html",
      catering_id: cid,
      id: food_id,
      food: changeset,
      food_types: parse_food_types(Server.Catering.list_food_types())
    )
  end

  def update(conn, %{"id" => food_id, "catering_id" => cid, "food" => food_params}) do
    food = Server.Catering.get_food!(food_id)

    case Server.Catering.update_food(food, food_params) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Успешно обовена информация за храната!")
        |> redirect(to: Routes.catering_catering_food_path(conn, :show, cid, food_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html",
          catering_id: cid,
          food: changeset,
          food_types: parse_food_types(Server.Catering.list_food_types())
        )
    end
  end

  def delete(conn, %{"id" => id, "catering_id" => cid}) do
    {:ok, _} =
      id
      |> Server.Catering.get_food!()
      |> Server.Catering.delete_food()

    conn
    |> put_flash(:info, "Храната бе премахната успешно!")
    |> redirect(to: Routes.catering_catering_food_path(conn, :index, cid))
  end

  defp parse_food_types(food_types) do
    Enum.map(food_types, fn %FoodType{name: name, id: id} -> {name, id} end)
  end
end

lib/server_web/controllers/catering/catering_menu_controller.ex
defmodule ServerWeb.CateringMenuController do
  use ServerWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html", menus: Server.Catering.list_menus)
  end

  def new(conn, id) do
    menu = Server.Catering.change_menu(%Server.Catering.Menu{})
    id = id["catering_id"]
    render(conn, "new.html", menu: menu, id: id, starters: Server.Catering.get_starters(id), mains: Server.Catering.get_main(id), desserts: Server.Catering.get_dessert(id))
  end

  def create(conn, params) do

    catering_id = params["catering_id"]
    date = params["menu"]["date"]
    dessert = params["menu"]["dessert"]
    main = params["menu"]["main"]
    starter = params["menu"]["starter"]
    map = %{
      date: date,
      dessert_id: String.to_integer(dessert),
      main_id: String.to_integer(main),
      starter_id: String.to_integer(starter),
      catering_id: String.to_integer(catering_id)
    }
    Server.Catering.new_menu(map)
    render(conn, "index.html", menus: Server.Catering.list_menus)
  end

  def show(conn, params) do
    id = params["id"]
    menu = Server.Catering.get_menu(id)
    render(conn, "show.html", menu: menu)
  end

  def edit(conn, %{"catering_id" => cid, "menu_id" => mid} = params) do
    redirect(conn, to: Routes.catering_catering_menu_path(conn, :edit, cid, mid, params))
  end

  def update(conn, %{"catering_id" => cid, "menu_id" => mid} = params) do
    redirect(conn, to: Routes.catering_catering_menu_path(conn, :update, cid, mid, params))
  end

  def delete(conn, %{"catering_id" => cid, "menu_id" => mid} = params) do
    redirect(conn, to: Routes.catering_catering_menu_path(conn, :delete, cid, mid, params))
  end

  def delete(conn, %{"id" => id}) do
    Server.Catering.delete_menu(id)

    render(conn, "index.html", menus: Server.Catering.list_menus)
  end
end

lib/server_web/controllers/catering/catering_order_controller.ex
defmodule ServerWeb.CateringOrderController do
  use ServerWeb, :controller

  def index(conn, %{"catering_id" => _cid} = params) do
    render(conn, "index.html", params)
  end

  def new(conn, %{"catering_id" => _cid} = params) do
    render(conn, "new.html", params)
  end

  def create(conn, %{"catering_id" => _cid} = params) do
    render(conn, "index.html", params)
  end

  def show(conn, %{"catering_id" => _cid, "order_id" => _oid} = params) do
    render(conn, "show.html", params)
  end

  def edit(conn, %{"catering_id" => cid, "order_id" => oid} = params) do
    redirect(conn, to: Routes.catering_catering_order_path(conn, :edit, cid, oid, params))
  end

  def update(conn, %{"catering_id" => cid, "order_id" => oid} = params) do
    redirect(conn, to: Routes.catering_catering_order_path(conn, :update, cid, oid, params))
  end

  def delete(conn, %{"catering_id" => cid, "order_id" => oid} = params) do
    redirect(conn, to: Routes.catering_catering_order_path(conn, :delete, cid, oid, params))
  end
end

lib/server_web/views/catering/catering_food_view.ex
defmodule ServerWeb.CateringFoodView do
  use ServerWeb, :view
  def get_food_id(%Server.Catering.Food{id: id}), do: id

  def get_food_type_by_id(%Server.Catering.Food{food_type: id}),
    do: Server.Catering.get_food_type!(id).name
end

lib/server_web/views/catering/catering_menu_view.ex
defmodule ServerWeb.CateringMenuView do
  use ServerWeb, :view
end

lib/server_web/views/catering/catering_order_view.ex
defmodule ServerWeb.CateringOrderView do
  use ServerWeb, :view
end

lib/server_web/views/catering/catering_view.ex
defmodule ServerWeb.CateringView do
  use ServerWeb, :view
end

lib/server_web/templates/catering/edit.html.eex
<h1>Промяна на профил</h1>

<%= render "form.html", action: Routes.catering_path(@conn, :update, @catering), cities: @cities, changeset: @changeset   %>

<span><%= link "Back", to: Routes.catering_path(@conn, :index) %></span>

lib/server_web/templates/catering/form.html.eex
<div class="row">
    <div class="form-outline">
        <div class="title">Регистрация на кетъринг фирма</div>
        <%= form_for @changeset, @action,[class: "reg-forms"], fn f -> %>
            <%= text_input f, :name, [ class: "form-control" , required: true , placeholder: "Лично име",  type: "text"] %>
            <%= select f, :city, @cities %>

                <%= inputs_for f, :credential, fn cf -> %>
                    <%= text_input cf, :email, [ class: "form-control" , required: true , placeholder: "Имейл адрес",  type: "email"] %>
                    <%= text_input cf, :username, [ class: "form-control" ,minlength: "8", required: true , placeholder: "Потребителско име",  type: "text",value: ""] %>
                    <%= text_input cf, :password, [ class: "form-control" ,minlength: "8", required: true , placeholder: "Парола",  type: "password", value: ""] %>
                    <%= text_input cf, :password_confirmation, [ class: "form-control" ,minlength: "8", required: true , placeholder: "Повторете паролата",  type: "password", value: ""] %>
                <% end %>
            
                <%= inputs_for f, :address, fn address -> %>
                    <%= hidden_input address, :country, [ class: "form-control", required: true ,value: "България"] %>
                    <%= hidden_input address, :city, [ class: "form-control", value: ""] %>
                    <%= hidden_input address, :province, [ class: "form-control", value: ""] %>
                    <%= text_input address, :address, [ class: "form-control" , placeholder: "Адрес", required: true ,  type: "text"] %>
                    <%= text_input address, :post_code, [ class: "form-control" ,placeholder: "Пощенски код", required: true ,  type: "number"] %>
                <%end%>


            <div>
                <%= submit "Регистрирай" , class: "btn btn-primary"  %>
            </div>
        <% end %>
    </div>
</div>

lib/server_web/templates/catering/index.html.eex
<style>
  .form-outline{
    width: 100%;
    margin: 0px;
  }
  .reg-forms{
    margin-top: 5%;
    width: 50%;
    margin-left: 25%;
  }
</style>
<div class="row">
  <div class="form-outline">
  <div class="title">Всички регистрирани кетъринг фирми</div>
  <span><%= link "Нов кетъринг акаунт", to: Routes.catering_path(@conn, :new), class: "btn btn-primary" %></span>
  <table>
    <thead>
      <tr>
        <th>Име</th>

        <th>Адрес</th>

        <th>Опции</th>
      </tr>
    </thead>
    <tbody>
    <%= for catering <- @caterings do %>
        <% address = Server.Repo.preload(catering, :address).address %>
        <tr>
        
          <td><%= catering.name %></td>
          <td><%= "#{address.city}, #{address.address}" %>
          <td>
            <%= link to: Routes.catering_path(@conn, :delete, catering), method: :delete, data: [confirm: "Are you sure?"] do %>
              <i class="fas fa-trash" style="font-size: 30px;"></i>
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
  </div>
</div>

lib/server_web/templates/catering/new.html.eex
<%= render "form.html", Map.put(assigns, :action, Routes.catering_path(@conn, :create)) %>

lib/server_web/templates/catering/registration.html.eex
<div class="row">
    <div class="form-outline">
    <div class="title">Регистрация на кетъринг фирма</div>

        <%= form_for @conn, Routes.catering_path(@conn , :create),[ method: :post, as: :registration, class: "reg-forms" ], fn form -> %>
        <%= inputs_for form, :catering, fn catering -> %>
        <div class="col-xs-12">
            <span class="form-control">Наименование на кетъринг фирмата:</span>
            <%= text_input catering, :name, [ class: "form-control" ,minlength: "3", required: true , placeholder: "Наименование на кетъринг фирмата",  type: "text" , value: "Кетъринг-"] %>
            <span class="form-control">Град:</span>
            <%= text_input catering, :city, [ class: "form-control" ,minlength: "3", required: true , placeholder: "Наименование на кетъринг фирмата",  type: "text" , value: "Варна" , readonly: true] %>
        </div>
        <%= inputs_for catering, :credential, fn credential -> %>
        <span class="form-control">Потребителско име:</span>
        <%= text_input credential, :username, [ class: "form-control" ,minlength: "8", required: true , placeholder: "Потребителско име",  type: "text",value: "Кетъринг-"] %>
        <span class="form-control">Парола:</span>
        <%= text_input credential, :password, [ class: "form-control" ,minlength: "8", required: true , placeholder: "Парола",  type: "password",value: "123123123"] %>
        <span class="form-control">Повторете паролата:</span>
        <%= text_input credential, :password_confirmation, [ class: "form-control" ,minlength: "8", required: true , placeholder: "Повторете паролата",  type: "password",value: "123123123"] %>
        <% end %>
        <% end %>
        <button class="btn btn-primary">Регистрирай</button>
        <% end %>
    </div>
</div>

lib/server_web/templates/catering/show.html.eex
<div class="show-info">
    <div class="inner">
        <div class="left">
            <div class="container-title">Профил</div>
            <div class="data">
                <div class="data-element">
                    <span class="name">Име:</span> <span class="name-data"><%= @catering.name %></span>
                </div>
                <div class="data-element">
                    <span class="name">Потребителско име:</span> <span class="name-data"><%= @catering.credential.username %></span>
                </div>
                <div class="data-element">
                    <span class="name">И-мейл:</span> <span class="name-data"><%= @catering.credential.email %></span>
                </div>
                <div class="data-element">
                    <span class="name">Град:</span> <span class="name-data"><%= Server.Accounts.get_address(@conn.assigns.catering.address_id).city %></span>
                </div>
            </div>
        </div>

        <div class="right">
            <div class="container-title">Опции</div>
            <div class="data">
                <div class="link"><%= link "Храни", to: Routes.catering_catering_food_path(@conn, :index, @catering) %></div>
                <div class="link"><%= link "Менюта", to: Routes.catering_catering_menu_path(@conn, :index, @catering.id) %></div>
                <div class="link"><%= link "Поръчки", to: Routes.catering_order_path(@conn, :orders, @catering.id) %></div>
            </div>
        </div>
    </div>
</div>